id: medcom.fhir.dk.fhirexample
canonical: http://medcomfhir.dk/ig/fhirexample
name: ExampleIG
title: Example Title
description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: draft
publisher:
  name: MedCom
  url: http://www.medcom.dk
menu:
  Home: index.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true

