@startuml DocumentModel

hide empty members

class "MedComDocumentBundle" as document
class "MedComDocumentComposition" as composition
class "MedComDocumentOrganization" as organization <<MedComCoreOrganization>>
class "MedComDocumentPractitioner" as practitioner <<MedComCorePractitioner>>
class "MedComDocumentPatient" as patient <<DkCorePatient>>
class "*use case specific content*" as clinical

document -- composition : "entry"
composition -- organization : "authorInstitution"
composition -- practitioner : "authorPerson"
composition -- patient : "subject"
composition -- clinical : "section.entry"


@enduml