@startuml
actor "Content Retriever" as CR
participant "Document Consumer" as DC
participant "On-Demand Document Source" as ODDS

CR -> DC: Obtain necessary document(s) information from use case R1
DC -> ODDS: Submit request (ITI-43)
ODDS -> ODDS: Validate request
ODDS -> ODDS: Produce document
ODDS -> DC: Return requested document(s) (ITI-43)
@enduml
