@startuml
actor "Content Retriever" as CR
participant "Document Consumer" as DC
participant "Document Registry" as DReg

CR -> DC: Trigger to perform query
DC -> DC: Identify search parameters
DC -> DReg: Submit request with parameters (ITI-18)
DReg -> DReg: Verify included parameters
DReg -> DC: Return metadata response (ITI-18)
@enduml
